version: "3.8"

services:
  # Serviço MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb-gestao-fiscal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gestao-fiscal-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da Aplicação Node.js
  app:
    build: .
    container_name: app-gestao-fiscal
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - NODE_ENV=production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - gestao-fiscal-network

volumes:
  mongodb_data:

networks:
  gestao-fiscal-network:
    driver: bridge
